### ISSUE TITLE
truffle test error : only owner can mint

### ISSUE THREAD

**Issue by 3for** [pointtoken/Contracts#2]
I use '$truffle test’ ， and get the following information, how to get it passed? Any help appreciated. 
Contract: PointToken
    √ should have a name (97ms)
    √ should have an owner (87ms)
    √ can mint (132ms)
    √ can add awarder  (120ms)
    √ can add award (229ms)
    √ can award achievement (214ms)
    √ can award achievement without giving any tokens (285ms)
    √ can not take over someone elses award (233ms)
    √ can lookup award (76ms)
    √ can remove awarder  (147ms)
    √ can check that random user is not awarder (75ms)
    1) only owner can mint
    > No events were emitted

  11 passing (2s)
  1 failing

  1) Contract: PointToken only owner can mint:
     AssertionError: Did not receive expected error message
      at PointToken.new.then.then.then.catch (test\PointTokenTests.js:171:17)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by 3for** [comment]
It is run as expected. See the following explaination:
https://github.com/OpenZeppelin/zeppelin-solidity/issues/584
https://ethereum.stackexchange.com/questions/15166/difference-between-require-and-assert-and-the-difference-between-revert-and-thro
